server:
  port: 8080

spring:
  application:
    name: pokehub

pokeapi:
  base-url: https://pokeapi.co/api/v2

tcgdex:
  base-url: https://api.tcgdex.net/v2/es

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash
  base-url: https://generativelanguage.googleapis.com/v1beta
  enabled: true
  max-input-length: 12000